# Generated by Django 3.2.8 on 2021-10-22 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_alter_statistic_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
